server {
    # Listen only on HTTPS (Inception rule)
    listen 443 ssl;

    # domain name 
    server_name moel-yag.42.fr;

    # SSL Configuration (Strictly TLS 1.2 and 1.3)
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    # Where the website files live
    root /var/www/html/wordpress;
    index index.php index.html index.htm;

    # Route standard requests (Check if file exists, else 404 error)
    location / {
      try_files $uri $uri/ /index.php?$args;
    }

    # Route PHP requests to the WordPress container
    location ~ \.php$ {
        # This is the line that links the containers:
        fastcgi_pass wordpress:9000;
        # add metadata for the request headers
        include fastcgi_params;
        # folder root and uri script name
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
