; a worker pool 
[www]

; Security: Drop root privileges and run PHP processes as the restricted www-data user
user = www-data
group = www-data

; Restrict the communication port so only the www-data user can access it
listen = 9000

; controle who can use the port 
listen.owner = www-data
listen.group = www-data

; pm (process manager to set how many workers that can work)
; tells php to automaticly scale the number of active workers depending on website traffic
pm = dynamic

; the max workers that the server allow to use
pm.max_children = 5

; When the container first boots, immediately spawn 2 workers to stand by.
pm.start_servers = 2 

; during quiet time just let one idle worker awake but has nothing to do 
pm.min_spare_servers = 1

; this when a small traffic on the website decrease the number of workers to 3
pm.max_spare_servers = 3

; tell wordpress workers to not delete the envirenement
clear_env = no
